/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BraggoscopeSearch {
    }
}
declare global {
    interface HTMLBraggoscopeSearchElement extends Components.BraggoscopeSearch, HTMLStencilElement {
    }
    var HTMLBraggoscopeSearchElement: {
        prototype: HTMLBraggoscopeSearchElement;
        new (): HTMLBraggoscopeSearchElement;
    };
    interface HTMLElementTagNameMap {
        "braggoscope-search": HTMLBraggoscopeSearchElement;
    }
}
declare namespace LocalJSX {
    interface BraggoscopeSearch {
    }
    interface IntrinsicElements {
        "braggoscope-search": BraggoscopeSearch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "braggoscope-search": LocalJSX.BraggoscopeSearch & JSXBase.HTMLAttributes<HTMLBraggoscopeSearchElement>;
        }
    }
}
